import {Inter} from 'next/font/google'
import './globals.css'
import Menu from "@/components/menu/Menu";
import 'react-multi-carousel/lib/styles.css';

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Tv app',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Menu>
                    {children}
                </Menu>
            </body>
        </html>
    )
}